config/routes.rb
Rails.application.routes.draw do
  devise_for :users
get "/jquery-1" => "pages#jquery_1"
get "/jquery-2" => "pages#jquery_2"
get "/jquery-3" => "pages#jquery_3"
get "/jquery-4" => "pages#jquery_4"
get "/jquery-5" => "pages#jquery_5"

resources :posts do
  member do
    post "like" => "posts#like"
    post "unlike" => "posts#unlike"
  end
end

root "posts#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :content
  belongs_to :user

  has_many :likes, :dependent => :destroy
  has_many :liked_users, :through => :likes, :source => :user

  def find_like(user)
    self.likes.where(:user_id => user.id).first
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  has_many :likes, :dependent => :destroy
  has_many :liked_posts, :through => :likes, :source => :post
  
  def display_name
    # # 取 email 的前半来显示，如果你也可以另开一个字段是nickname让用户可以编辑自己编辑
    self.email.split("@").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :destroy]

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save
  end

  def destroy
    @post = current_user.posts.find(params[:id])#只能删除自己的贴文
    @post.destroy

  end

  def index
    @posts = Post.order("id DESC").all #新贴文放前面
  end

  def like
    @post = Post.find(params[:id])
    unless @post.find_like(current_user) # 如果已经按赞过了，就略过不再新增
      Like.create( :user => current_user, :post => @post)
    end
  end

  def unlike
    @post = Post.find(params[:id])
    like = @post.find_like(current_user)
    like.destroy
    render "like"
  end

  protected

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxPostingApp1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "jQuery 练习一", jquery_1_path %> |
    <%= link_to "jQuery 练习二", jquery_2_path %> |
    <%= link_to "jQuery 练习三", jquery_3_path %> |
    <%= link_to "jQuery 练习四", jquery_4_path %> |
    <%= link_to "jQuery 练习五", jquery_5_path %>

    <% if flash[:notice] %>
     <%= flash[:notice] %>
    <% end %>

   <% if flash[:alert] %>
     <%= flash[:alert] %>
   <% end %>

  <% if current_user %>
     <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
     <%= link_to('修改密码', edit_registration_path(:user)) %>
  <% else %>
     <%= link_to('注册', new_registration_path(:user)) %> |
     <%= link_to('登入', new_session_path(:user)) %>
   <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/jquery_1.html.erb
<p>
  <a id="my-click">Click Me</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<script>
  $("#my-click").click(function(){
    $("#foo").after('<h1>zoo</h1>');
  })
</script>

app/views/pages/jquery_2.html.erb
<p>
  <a id="my-open-click">Open</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <a id="my-slideUp-click">slideUp</a>
  <p>bar</p>
</div>


<script>
  $("#foo").slideUp();

  $("#my-open-click").click(function(){
    $("#foo").slideDown();
  })

  $("#my-slideUp-click").click(function(){
    $("#foo").slideUp();
  })
</script>

app/views/pages/jquery_3.html.erb
<p>
  <a id="my-fadeToggle-click">Toggle</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<script>
  $("#foo").hide();   // 先马上藏起来

  $("#my-fadeToggle-click").hover(function(){
    $("#foo").fadeToggle();   // 移过去会有开关的效果
  })

</script>

app/views/pages/jquery_4.html.erb
<p>
  <a id="my-replace-click">Replace</a>
  <a id="my-remove-click">Remove</a>
  <a id="my-remove-all-click">Remove All</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<div class="zoo"><p>a</p></div>
<div class="zoo"><p>b</p></div>
<div class="zoo"><p>c</p></div>

<script>
  $("#my-replace-click").click(function(){
    $("#foo").replaceWith('<div id="foo" style="border:1px solid green"><p>foo</p></div>');
  })

  $("#my-remove-click").click(function(){
    $("#foo").remove();
  })

  $("#my-remove-all-click").click(function(){
    $(".zoo").remove();
  })
</script>

app/views/pages/jquery_5.html.erb
<style>
  .error {
    color: red;
  }
  .success {
    color: green;
  }
</style>

<p>
  <a id="my-add-class-click">Add Class</a>

  <a id="my-remove-class-click">Remove Class</a>
</p>

<div id="foo">
  <h1>bar</h1>
</div>

<script>
  $("#my-add-class-click").click(function(){
    $("#foo").removeClass('error');
    $("#foo").addClass('success');
  })

  $("#my-remove-class-click").click(function(){
    $("#foo").removeClass('success');
    $("#foo").addClass('error');
  })
</script>

app/views/posts/_like.html.erb
<% if post.liked_users.any? %>
  <%= post.liked_users.map{ |u| u.display_name }.join(",") %> 点了赞
<% end %>

<% if current_user # 有登入才可以按讚 %>
  <% if post.find_like(current_user) %>
    <%= link_to "取消讚", unlike_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
  <% else %>
    <%= link_to "讚", like_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class="panel panel-default">

  <div class="panel-heading">
    <%= post.user.display_name %>
  </div>
  <div class="panel-body">
    <span id="post-thumbsup-<%= post.id %>" class="label label-success"><%= post.likes.count %> 👍</span>
    <%= post.content %>
     <div class="text-right">
   <span id="post-like-<%= post.id %>">
     <%= render :partial => "like", :locals => { :post => post} %>
   </span>
       <!-- <% if post.liked_users.any? %>
       <%= post.liked_users.map{ |u| u.display_name }.join(",") %> 点了赞
       <% end %>
    <% if current_user # 有登入才可以按赞 %>
      <% if post.find_like(current_user) %>
        <%= link_to "-1", unlike_post_path(post), :method => :post, :class => "btn btn-primary" %>
      <% else %>
        <%= link_to "1", like_post_path(post), :method => :post, :class => "btn btn-primary" %>
      <% end %>
    <% end %> -->
    <% if current_user && post.user == current_user %>
        <%= link_to "Delete", post_path(post), :method => :delete, :class => "btn btn-danger", :remote => true %>
    <% end %>
  </div>
  </div>
</div>

app/views/posts/create.js.erb
<% if @post.valid? %>
  $("#post-list").prepend("<%= j render :partial => "post", :locals => { :post => @post } %>");
  $("#post_content").val("")
<% else %>
  alert("贴文失败");
<% end %>

app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").remove();

app/views/posts/index.html.erb
 <%= form_for Post.new, :remote => true do |f| %>
   <div class="form-group">
     <%= f.text_area :content, :class => "form-control" %>
   </div>
   <div class="form-group">
     <%= f.submit :class => "btn btn-primary" %>
   </div>
 <% end %>

<div id="post-list">
<% @posts.each do |post| %>

 <div id="post-<%= post.id %>" class="panel panel-default">
    <!-- <div class="panel-heading">
     <%= post.user.display_name %>
    </div>
    <div class="panel-body">
     <%= post.content %>
        <div class="text-right">

      <% if post.liked_users.any? %>
        <%= post.liked_users.map{ |u| u.display_name }.join(",") %> 点了赞
      <% end %>

      <% if current_user # 有登入才可以按讚 %>
        <% if post.find_like(current_user) %>
          <%= link_to "-1", unlike_post_path(post), :method => :post, :remote => true,:class => "btn btn-primary" %>
        <% else %>
          <%= link_to "+1", like_post_path(post), :method => :post,:remote => true, :class => "btn btn-primary" %>
        <% end %>
      <% end %>

      <% if current_user && post.user == current_user %>
          <%= link_to "Delete", post_path(post), :method => :delete, :class => "btn btn-danger", :remote => true %>
      <% end %>
    </div>
  </div> -->
</div>

<% end %>

app/views/posts/like.js.erb
str = "<%=j render :partial => "like", :locals => { :post => @post } %>";
$("#post-like-<%= @post.id %>").html(str);
$("#post-thumbsup-<%= @post.id %>").html("<%= @post.likes.count %>" + " 👍");